// Mock data for development purposes
export const MOCK_BIKES = [
    {
      id: '1',
      name: 'Eco Boda Max',
      image: 'https://thefounder.africa/content/images/2024/04/Bolt-electric-bike.png',
      brand: 'Ampersand',
      type: 'passenger',
      price: 450,
      range: 80,
      availability: 'available',
      description: 'Perfect for carrying passengers through urban areas with its comfortable seat and sturdy frame. Features regenerative braking for extended range.',
      specs: {
        motor: '1500W',
        battery: '48V 20Ah',
        chargingTime: '4 hours',
        maxSpeed: '45 km/h',
        loadCapacity: '180 kg',
      },
    },
    {
      id: '2',
      name: 'Power Delivery',
      image: 'https://thefounder.africa/content/images/2024/04/Bolt-electric-bike.png',
      brand: 'Roam Air',
      type: 'delivery',
      price: 500,
      range: 90,
      availability: 'limited',
      description: 'Designed specifically for delivery services with extra storage capacity and durable construction. Features quick-swap battery system.',
      specs: {
        motor: '1800W',
        battery: '60V 30Ah',
        chargingTime: '3.5 hours',
        maxSpeed: '50 km/h',
        loadCapacity: '200 kg',
      },
    },
    {
      id: '3',
      name: 'Urban Commuter',
      image: 'https://thefounder.africa/content/images/2024/04/Bolt-electric-bike.png',
      brand: 'ARC Ride',
      type: 'standard',
      price: 400,
      range: 70,
      availability: 'available',
      description: 'Efficient and cost-effective option for daily commuting in urban environments. Lightweight design with essential features.',
      specs: {
        motor: '1200W',
        battery: '48V 15Ah',
        chargingTime: '3 hours',
        maxSpeed: '40 km/h',
        loadCapacity: '150 kg',
      },
    },
    {
      id: '4',
      name: 'Heavy Hauler',
      image: 'https://thefounder.africa/content/images/2024/04/Bolt-electric-bike.png',
      brand: 'Opibus',
      type: 'cargo',
      price: 550,
      range: 65,
      availability: 'available',
      description: 'Built for heavy cargo transport with reinforced frame and powerful motor. Includes spacious rear cargo platform.',
      specs: {
        motor: '2000W',
        battery: '72V 30Ah',
        chargingTime: '5 hours',
        maxSpeed: '35 km/h',
        loadCapacity: '250 kg',
      },
    },
    {
      id: '5',
      name: 'Eco Express',
      image: 'https://thefounder.africa/content/images/2024/04/Bolt-electric-bike.png',
      brand: 'Ampersand',
      type: 'passenger',
      price: 480,
      range: 85,
      availability: 'unavailable',
      description: 'Premium passenger model with enhanced comfort and safety features. Includes USB charging for mobile devices.',
      specs: {
        motor: '1600W',
        battery: '60V 25Ah',
        chargingTime: '4.5 hours',
        maxSpeed: '45 km/h',
        loadCapacity: '170 kg',
      },
    },
  ];
  
  export const MOCK_SWAP_STATIONS = [
    {
      id: '1',
      name: 'Metro Energy Hub',
      latitude: -1.286389,
      longitude: 36.817223,
      distance: 1.2,
      batteryAvailable: 8,
      openUntil: '22:00',
      address: 'Kenyatta Avenue, Nairobi',
    },
    {
      id: '2',
      name: 'GreenPower Exchange',
      latitude: -1.291389,
      longitude: 36.821223,
      distance: 2.5,
      batteryAvailable: 3,
      openUntil: '20:00',
      address: 'Moi Avenue, Nairobi',
    },
    {
      id: '3',
      name: 'Quick Swap Station',
      latitude: -1.281389,
      longitude: 36.812223,
      distance: 3.7,
      batteryAvailable: 0,
      openUntil: '23:00',
      address: 'Tom Mboya Street, Nairobi',
    },
    {
      id: '4',
      name: 'EcoBoda Power Point',
      latitude: -1.296389,
      longitude: 36.822223,
      distance: 4.1,
      batteryAvailable: 12,
      openUntil: '21:00',
      address: 'Ngara Road, Nairobi',
    },
    {
      id: '5',
      name: 'Charging Corner',
      latitude: -1.301389,
      longitude: 36.827223,
      distance: 5.3,
      batteryAvailable: 2,
      openUntil: '19:00',
      address: 'Haile Selassie Avenue, Nairobi',
    },
  ];
  
  export const MOCK_REPAIRS = [
    {
      id: '1',
      name: 'Boda Tech Garage',
      rating: 4.8,
      distance: 2.3,
      services: ['Motor Repair', 'Battery Service', 'Electronics'],
      image: 'https://images.unsplash.com/photo-1631972241361-330c704b90f1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
    {
      id: '2',
      name: 'EV Wheel Clinic',
      rating: 4.5,
      distance: 3.7,
      services: ['Tire Service', 'Brake Repair', 'Frame Work'],
      image: 'https://images.unsplash.com/photo-1631972241361-330c704b90f1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
    {
      id: '3',
      name: 'Power Cycle Repairs',
      rating: 4.9,
      distance: 1.5,
      services: ['Battery Replacement', 'Electrical Systems', 'General Service'],
      image: 'https://images.unsplash.com/photo-1631972241361-330c704b90f1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
  ];
  
  export const MOCK_USER = {
    id: '1',
    name: 'Eli Keli',
    phone: '+254 712 345 678',
    currentBike: '1', // References a bike ID
    paymentDue: 450,
    nextPaymentDate: '2025-06-15',
    paymentHistory: [
      { date: '2025-06-08', amount: 450, status: 'paid' },
      { date: '2025-06-01', amount: 450, status: 'paid' },
      { date: '2025-05-25', amount: 450, status: 'paid' },
    ],
    swapHistory: [
      { date: '2025-06-10', station: 'Metro Energy Hub', batteryLevel: '20%' },
      { date: '2025-06-07', station: 'GreenPower Exchange', batteryLevel: '15%' },
      { date: '2025-06-04', station: 'Metro Energy Hub', batteryLevel: '18%' },
    ],
  };